// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SRC.Persistence;

#nullable disable

namespace BJCPProject.Migrations
{
    [DbContext(typeof(BeerContext))]
    partial class BeerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SRC.Models.Estilo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("ABV")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("Aparencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aroma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comentarios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComparacaoDeEstilos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etiqueta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Historia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IBU")
                        .HasColumnType("int");

                    b.Property<string>("ImpressaoGeral")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IngredientesCaracteristicos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SRM")
                        .HasColumnType("int");

                    b.Property<string>("Sabor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SensacaoDeBoca")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estilos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ABV = 4.2m,
                            IBU = 12,
                            Nome = "American Light Lager",
                            SRM = 3
                        },
                        new
                        {
                            Id = 2,
                            ABV = 5.3m,
                            IBU = 18,
                            Nome = "American Lager",
                            SRM = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
